### ISSUE TITLE
Resources on Path Laplacian NLL

### ISSUE THREAD

**Issue by ayushmankumar7** [nikebless/openpilot-pipeline#22]
I read your read me file, where you said that guys at Comma helped you build the Path Laplacian NLL loss. Can you share any literature or group of literature which have been referred  building this loss function. 

I was actually researching on this topic. It would be a major help. Thank you :)

**Comment by zorrobyte** [comment]
@ayushmankumar7 there is a #custom-models channel on the comma discord, check it out!
