### ISSUE TITLE
Nuances and differences about the model

### ISSUE THREAD

**Issue by QSLee-Net** [nikebless/openpilot-pipeline#23]
Hello, author. Through your open source program, I can really train a new distillation model. I very much agree with your work and contribution in this field. However, there is a small problem to ask. The model I trained is slightly different from the original official model. Have you encountered it? Please see the picture for details, and expect to get and.
![2022-05-24 08-48-53屏幕截图](https://user-images.githubusercontent.com/88867460/169927948-2e995060-b767-4836-957c-8eb9581aba39.png)

**Comment by gautamjain1009** [comment]
As you can see from our code we are using their pre-trained model, to train only for the path plan. We did not change the architecture of the network, though we did not visualize the trained distillation model. Are you trying to train for lanelines also? I think you might have added some operations on the output of some layers for your case. That is why it can be seen in the computational graph. If that is not the case and you have not changed the code a bit and using the pre-trained model as it is, one thing I would suggest you try some different visualization tools. 
Anyhow I will recheck it myself and get back to you.

**Comment by QSLee-Net** [comment]
I'm glad to receive your reply. According to your reply, I have some ideas to exchange.

1. There is only one place where I modify the code. See the figure below for details. This is because the performance of my computer is not particularly good. There is no server to use. The purpose of modifying it is to make the code run, although I don't know why. But I think this is a data loading processing thread. Just CPUs allocation，that will not affect the model structure.
![2022-05-24 15-24-44屏幕截图](https://user-images.githubusercontent.com/88867460/169977955-b92ba29a-a24e-49d0-a7ee-bdcd160f05da.png)
2. Compared with the official model, there are six more branches, as described in the picture I sent you for the first time. The six structures are similar, and the corresponding code is in the following picture. You can see that the code corresponds to the number one by one.
![2022-05-24 15-25-38屏幕截图](https://user-images.githubusercontent.com/88867460/169978587-066fa0e7-b06e-4a36-a428-2a55319b73d2.png)
3. You can see that the six extra branches correspond to six pieces of code, which is really the problem here, but I don't know how to modify it. Moreover, the variable seems to be 0, that is, it doesn't work. Such a model can actually work normally. Even so, I still want to know how to deal with this problem. And I don't think it's a problem with visualization tools, although I'll try other tools in the future.
![2022-05-24 15-27-45屏幕截图](https://user-images.githubusercontent.com/88867460/169979415-1c0df91e-f742-4372-a8ad-b56ccdf82e8a.png)

**Comment by gautamjain1009** [comment]
Sorry for the late reply! 
We used [onnx2Pytorch](https://github.com/ToriML/onnx2pytorch) for loading the pretrained supercombo model , the main issue at that time with [onnx2Pytorch](https://github.com/ToriML/onnx2pytorch), it was not able to handle the training with batch_size>1 as you can also take a look on their GitHub repo as mentioned. So to enable the batch_size greater than one we did some tweaks in the respective layers that we want to train ie. in our case the layers responsible for the path plan. Further you can find in the mentioned commit a [file](https://github.com/nikebless/openpilot-pipeline/blob/c6822daf916c10a9c74a973b75bf8abdcd4dbe2c/compare_models.py) where we compared the inference predictions from onnxruntime and onnx2Pytroch. So we figured it out there was some problem in one Relu layer, somehow inpace=True was changing the predictions, that also you can track in the commit history. So by turning it off the model performed normally for us with onnx2Pytorch. Apart from that  
When you go to this previous [commit](https://github.com/nikebless/openpilot-pipeline/blob/c6822daf916c10a9c74a973b75bf8abdcd4dbe2c/train/train.py  ).  

`pytorch_model.Constant_1047.constant= torch.tensor((batch_size, 2, 66))
 pytorch_model.Reshape_1048.shape = (batch_size, 2, 66)`
        
 to achieve this we replace the above code snippet just by 
 
 `model.Constant_1047.constant[0] = -1`  
 The value of the attribute in **3** is irrelevant to the scenario.
