### ISSUE TITLE
some of conv layers of supercombo model use groups > 1

### ISSUE THREAD

**Issue by likegogogo** [nikebless/openpilot-pipeline#24]
but in https://github.com/nikebless/openpilot-pipeline/blob/main/train/custom_model.py this implement, not conv use groups >1.

**Comment by gautamjain1009** [comment]
@ideafold Sorry for the late reply, While implementing the model I tried to mimic the model visualization from supercombo.onnx. There can be some discrepancy in that. Moreover we have not used this implementation for training.
